analyze_1l_2tau analyze_sync_1l_2tau_ttHJetToNonbb_M125_Fakeable_wFakeRateWeights_OS_cfg.py
analyze_2lss_1tau analyze_sync_2lss_1tau_ttHJetToNonbb_M125_Tight_SS_cfg.py
analyze_1l_2tau analyze_sync_1l_2tau_ttHJetToNonbb_M125_Tight_OS_cfg.py
analyze_3l_1tau analyze_sync_3l_1tau_ttHJetToNonbb_M125_Fakeable_wFakeRateWeights_OS_cfg.py
analyze_2lss_1tau analyze_sync_2lss_1tau_ttHJetToNonbb_M125_Fakeable_wFakeRateWeights_SS_cfg.py
analyze_3l_1tau analyze_sync_3l_1tau_ttHJetToNonbb_M125_Tight_OS_cfg.py
analyze_2lss_1tau analyze_sync_2lss_1tau_ttHJetToNonbb_M125_Tight_OS_cfg.py
