import FWCore.ParameterSet.Config as cms
import os, sys
sys.path.append("..")

from sync_ntuples_cfg import *

process.syncNtuple.selEventsFileName_input = cms.string('output/selEvents_ttHJetToNonbb_3l_1tau_M125_Tight_OS.txt')
process.syncNtuple.outputTreeName = cms.string('syncTree_3l1tau_SR')
process.fwliteOutput = cms.PSet(
    fileName = cms.string('/home/andres/tth/VHbbNtuples_8_0_x/CMSSW_8_0_19/src/tthAnalysis/HiggsToTauTau/test/sync/ntuple/sync_ntuple_3l_1tau_OS.root')
)

process.syncNtuple.process = cms.string('signal')
process.syncNtuple.histogramDir = cms.string('3l_1tau_OS_lepTight_tauTight')
process.syncNtuple.era = cms.string('2016')
process.syncNtuple.triggers_1e = cms.vstring(['HLT_BIT_HLT_Ele25_WPTight_Gsf_v', 'HLT_BIT_HLT_Ele25_eta2p1_WPTight_Gsf_v', 'HLT_BIT_HLT_Ele27_eta2p1_WPLoose_Gsf_v', 'HLT_BIT_HLT_Ele27_eta2p1_WPTight_Gsf_v'])
process.syncNtuple.use_triggers_1e = cms.bool(True)
process.syncNtuple.triggers_1mu = cms.vstring(['HLT_BIT_HLT_IsoMu22_v', 'HLT_BIT_HLT_IsoTkMu22_v', 'HLT_BIT_HLT_IsoMu22_eta2p1_v', 'HLT_BIT_HLT_IsoTkMu22_eta2p1_v'])
process.syncNtuple.use_triggers_1mu = cms.bool(True)
process.syncNtuple.triggers_2e = cms.vstring(['HLT_BIT_HLT_Ele23_Ele12_CaloIdL_TrackIdL_IsoVL_DZ_v'])
process.syncNtuple.use_triggers_2e = cms.bool(True)
process.syncNtuple.triggers_1e1mu = cms.vstring(['HLT_BIT_HLT_Mu23_TrkIsoVVL_Ele12_CaloIdL_TrackIdL_IsoVL_v', 'HLT_BIT_HLT_Mu8_TrkIsoVVL_Ele23_CaloIdL_TrackIdL_IsoVL_v'])
process.syncNtuple.use_triggers_1e1mu = cms.bool(True)
process.syncNtuple.triggers_2mu = cms.vstring(['HLT_BIT_HLT_Mu17_TrkIsoVVL_Mu8_TrkIsoVVL_DZ_v', 'HLT_BIT_HLT_Mu17_TrkIsoVVL_TkMu8_TrkIsoVVL_DZ_v'])
process.syncNtuple.use_triggers_2mu = cms.bool(True)
process.syncNtuple.triggers_3e = cms.vstring(['HLT_BIT_HLT_Ele16_Ele12_Ele8_CaloIdL_TrackIdL_v'])
process.syncNtuple.use_triggers_3e = cms.bool(True)
process.syncNtuple.triggers_2e1mu = cms.vstring(['HLT_BIT_HLT_Mu8_DiEle12_CaloIdL_TrackIdL_v'])
process.syncNtuple.use_triggers_2e1mu = cms.bool(True)
process.syncNtuple.triggers_1e2mu = cms.vstring(['HLT_BIT_HLT_DiMu9_Ele9_CaloIdL_TrackIdL_v'])
process.syncNtuple.use_triggers_1e2mu = cms.bool(True)
process.syncNtuple.triggers_3mu = cms.vstring(['HLT_BIT_HLT_TripleMu_12_10_5_v'])
process.syncNtuple.use_triggers_3mu = cms.bool(True)
process.syncNtuple.triggers_1e1tau = cms.vstring(['HLT_BIT_HLT_Ele24_eta2p1_WPLoose_Gsf_LooseIsoPFTau30_v'])
process.syncNtuple.use_triggers_1e1tau = cms.bool(False)
process.syncNtuple.triggers_1mu1tau = cms.vstring(['HLT_BIT_HLT_IsoMu19_eta2p1_LooseIsoPFTau20_SingleL1_v'])
process.syncNtuple.use_triggers_1mu1tau = cms.bool(False)
process.syncNtuple.leptonSelection = cms.string('Tight')
process.syncNtuple.apply_leptonGenMatching = cms.bool(True)
process.syncNtuple.hadTauSelection = cms.string('Tight|dR03mvaMedium')
process.syncNtuple.apply_hadTauGenMatching = cms.bool(True)
process.syncNtuple.applyFakeRateWeights = cms.string('disabled')
process.syncNtuple.hadTauFakeRateWeight.inputFileName = cms.string('tthAnalysis/HiggsToTauTau/data/FR_tau_2016.root')
process.syncNtuple.hadTauFakeRateWeight.lead.fitFunctionName = cms.string('jetToTauFakeRate/dR03mvaMedium/$etaBin/fitFunction_data_div_mc_hadTaus_pt')
process.syncNtuple.hadTauFakeRateWeight.applyGraph_lead = cms.bool(False)
process.syncNtuple.hadTauFakeRateWeight.applyFitFunction_lead = cms.bool(True)
process.syncNtuple.apply_hadTauFakeRateSF = cms.bool(True)
process.syncNtuple.chargeSumSelection = cms.string('OS')
process.syncNtuple.use_HIP_mitigation_bTag = cms.bool(True)
process.syncNtuple.use_HIP_mitigation_mediumMuonId = cms.bool(True)
process.syncNtuple.isMC = cms.bool(True)
process.syncNtuple.central_or_shift = cms.string('central')
process.syncNtuple.lumiScale = cms.double(0.002600)
process.syncNtuple.apply_genWeight = cms.bool(True)
process.syncNtuple.apply_trigger_bits = cms.bool(True)
#process.syncNtuple.selEventsFileName_output = cms.string('/home/veelken/ttHAnalysis/2016/2017Feb22/output_rle/3l_1tau/Tight_OS/ttHJetToNonbb_M125_amcatnlo/rle_3l_1tau_ttHJetToNonbb_M125_amcatnlo_Tight_OS_central_1.txt')
#process.syncNtuple.selEventsTFileName = cms.string('')
process.syncNtuple.selectBDT = cms.bool(False)
